services:
  - type: web
    name: drbleou-hybrid-trading
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PIP_PREFER_BINARY
        value: "1"
      - key: BITGET_API_KEY
        sync: false
      - key: BITGET_API_SECRET
        sync: false
      - key: BITGET_API_PASSPHRASE
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
